name: Build and Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:   
    - cron: '0 12 * * *'

jobs:
  build:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Use Node.js 21
      uses: actions/setup-node@v4.0.0
      with:
        node-version: 21
        cache: 'npm'
    - run: npm install 
    - run: npx playwright install      
    - run: npm run actions

  sonarcloud:
    name: Run SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 21 
      - name: Install SonarScanner CLI
        run: npm install -g sonar-scanner

      - name: SonarCloud Scan
        run: sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
